// ==========================================
// THEMES (with aligned clothing values)
// ==========================================
const THEMES = {
  'at-home':{ emoji:'🏠', name:'At Home', cameras:['soft natural light portrait photography','indoor natural light photography','candid lifestyle photography','documentary lifestyle photography','boudoir portrait photography','family portrait photography','romantic portrait photography'], props:['Coffee cup','Book','Pillow','Blanket','Candles','Tea cup','Journal notebook','Phone','Fairy lights','Stuffed animal','Teddy bear'], environments:['modern living room','cozy bedroom'], lighting:['warm window light','soft morning light','warm lamp light'], onePieces:['robe','nightgown','maxi dress'], tops:['sweater','hoodie','t-shirt'], bottoms:['leggings','joggers','yoga pants'], poses:['sitting comfortably','relaxed pose','lounging'], moods:['peaceful content mood','relaxed comfortable mood'], clothingPresets:['Cozy At-Home Set','Casual Coffee Run Set'] },
  'at-office':{ emoji:'💼', name:'Office', cameras:['professional portrait photography','commercial campaign photography','environmental portrait photography','documentary lifestyle photography','editorial fashion photography','high-end lifestyle photography'], props:['Laptop','Briefcase','Phone','Book','Coffee cup','Journal notebook'], environments:['office','conference room'], lighting:['bright overhead lighting','soft professional lighting'], onePieces:['A-line dress','shift dress','jumpsuit'], tops:['blazer','blouse','shirt'], bottoms:['dress pants','skirt'], poses:['standing confidently','professional pose'], moods:['confident heroic mood','elegant sophisticated mood'], occupations:['businesswoman','lawyer','architect'], clothingPresets:['Classic Office Set','Smart Casual Office Set'] },
  'on-vacation':{ emoji:'🏖️', name:'Vacation', cameras:['travel editorial photography','outdoor golden hour photography','candid lifestyle photography','high-end lifestyle photography','storytelling lifestyle photography','fashion catalog photography'], props:['Camera','Map','Luggage','Parasol','Flowers','Fruit bowl','Polaroid camera'], environments:['tropical beach','beach resort','ocean','cruise ship deck'], lighting:['golden hour sunset','bright natural sunlight','blue water reflections'], onePieces:['sundress','beach dress','maxi dress','swim cover-up','one-piece swimsuit'], tops:['tank top','camisole','bikini top','tankini top'], bottoms:['shorts','skirt','bikini bottoms','sarong'], poses:['standing confidently','walking naturally','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','happy relaxed mood'], clothingPresets:['Beach Cover-Up Set','Beach Lounge Set','Bikini Set','Resort Swim Set','Sunset Boardwalk Set'] },
  'beach-day':{ emoji:'🌊', name:'Beach Day', cameras:['outdoor golden hour photography','travel editorial photography','candid lifestyle photography','fashion catalog photography','action sports photography','sports editorial photography'], props:['Surfboard','Towel','Parasol','Ice cream cone','Flowers','Kite','Bubbles'], environments:['beach','boardwalk','ocean','tropical beach'], lighting:['backlit sunset','bright natural sunlight','golden hour sunset'], onePieces:['beach cover-up','one-piece swimsuit','swim cover-up'], tops:['bikini top','tankini top','triangle bikini top'], bottoms:['bikini bottoms','sarong','swim skirt'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['carefree lighthearted mood','joyful happy mood','happy relaxed mood'], clothingPresets:['Beach Cover-Up Set','Bikini Set','Resort Swim Set','Sunset Boardwalk Set'] },
  'prehistoric-jungle':{ emoji:'🦖', name:'Prehistoric / Jungle', cameras:['environmental portrait photography','documentary lifestyle photography','cinematic portrait photography','film-inspired portrait photography','storytelling lifestyle photography'], props:['Map','Lantern','Staff','Scroll','Artifact','Camp lantern'], environments:['dense jungle','jungle river','jungle ruins','prehistoric fern valley','rainforest waterfall','tropical jungle clearing','volcanic ridge'], lighting:['dappled sunlight through trees','golden hour sunset','humid misty light','soft diffused light'], onePieces:['explorer romper','survival wrap dress','utility jumpsuit'], tops:['linen shirt','mesh cover-up top','peasant blouse','tribal halter top','utility vest'], bottoms:['cargo pants','sarong','survival skirt','tailored shorts','utility shorts'], poses:['crouching slightly','standing confidently','strolling','walking naturally'], moods:['bold daring mood','fierce powerful mood','playful adventurous mood','wild untamed mood'], occupations:['adventurer','archaeologist','explorer','survivalist'], clothingPresets:['Explorer Jungle Set','Jungle Adventure Set','Prehistoric Huntress Set','Safari Linen Set','Tropical Waterfall Set'] },
  'coffee-cafes':{ emoji:'☕', name:'Coffee & Cafes', cameras:['candid lifestyle photography','indoor natural light photography','soft natural light portrait photography','documentary lifestyle photography','storytelling lifestyle photography'], props:['Coffee cup','Book','Journal notebook','Tea cup','Phone','Flowers','Single flower'], environments:['cafe','coffee shop','bookstore'], lighting:['warm cafe lighting','warm window light','natural daylight'], onePieces:['sundress','wrap dress','midi dress'], tops:['sweater','cardigan','blouse'], bottoms:['jeans','skirt','leggings'], poses:['sitting comfortably','relaxed pose'], moods:['peaceful content mood','relaxed comfortable mood'], clothingPresets:['Casual Coffee Run Set'] },
  'fitness':{ emoji:'🏋️', name:'Fitness', cameras:['action sports photography','sports editorial photography','documentary lifestyle photography','candid lifestyle photography','commercial campaign photography'], props:['Dumbbells','Yoga mat','Jump rope','Water bottle','Smoothie cup','Soccer ball','Tennis racket'], environments:['gym','yoga studio','spa'], lighting:['bright gym lighting','soft natural light'], onePieces:['bodysuit'], tops:['sports bra','tank top'], bottoms:['leggings','yoga pants','bike shorts'], poses:['yoga pose','stretching','standing confidently','warrior pose'], moods:['energetic vibrant mood','healthy active mood','fierce powerful mood'], clothingPresets:['Fitness Training Set'] },
  'nature':{ emoji:'🌲', name:'Nature', cameras:['outdoor golden hour photography','environmental portrait photography','storytelling lifestyle photography','documentary lifestyle photography','fine art portrait photography','aerial drone photography'], props:['Flowers','Watering can','Bouquet','Single flower','Kite','Umbrella','Picnic basket','Basket of fruit'], environments:['forest','flower field','mountain trail with pine trees','garden','meadow','lavender field'], lighting:['golden hour sunset','soft morning light','dappled sunlight through trees'], onePieces:['sundress','maxi dress'], tops:['t-shirt','cardigan'], bottoms:['jeans','shorts'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['peaceful serene mood','joyful happy mood','calm tranquil mood'], clothingPresets:['Boho Festival Set','Explorer Jungle Set','Safari Linen Set','Sunset Boardwalk Set'] },
  'creative':{ emoji:'🎭', name:'Creative', cameras:['fine art portrait photography','editorial fashion photography','film-inspired portrait photography','moody portrait photography','studio beauty photography','runway backstage photography'], props:['Paint palette','Sketchbook','Guitar','Violin','Acoustic guitar','Canvas painting','Film camera','Microphone','Pottery wheel','Musical instrument'], environments:['art studio','theater stage','art gallery','dance studio'], lighting:['soft studio lighting','stage lighting','warm lamp light'], onePieces:['wrap dress','jumpsuit','kimono'], tops:['blouse','crop top'], bottoms:['wide-leg pants','skirt'], poses:['standing confidently','dancing'], moods:['passionate intense mood','bold daring mood','dreamy ethereal mood'], occupations:['artist','dancer','musician','painter'], clothingPresets:['Boho Festival Set','Flowing Party Dress Set'] },
  'shopping':{ emoji:'🛍️', name:'Shopping', cameras:['editorial fashion photography','fashion catalog photography','street style photography','commercial campaign photography','high-end lifestyle photography','candid lifestyle photography'], props:['Shopping bags','Designer shopping bags','Purse','Phone','Coffee cup'], environments:['boutique','urban street','hotel lobby'], lighting:['natural daylight','bright overhead lighting'], onePieces:['midi dress','cocktail dress','A-line dress'], tops:['blazer','blouse','cardigan'], bottoms:['jeans','skirt','dress pants'], poses:['walking confidently','standing with hand on hip'], moods:['joyful happy mood','confident heroic mood','playful adventurous mood'], clothingPresets:['Casual Coffee Run Set','Smart Casual Office Set','Sunset Boardwalk Set'] },
  'fantasy':{ emoji:'🧚', name:'Fantasy', cameras:['cinematic portrait photography','fine art portrait photography','film-inspired portrait photography','moody portrait photography','editorial fashion photography'], props:['Staff','Scroll','Shield','Crystal ball','Lantern','Dreamcatcher','Candles','Flowers'], environments:['enchanted forest','gothic castle','medieval castle','throne room'], lighting:['magical glow','dramatic lighting','divine golden light','purple magical energy'], onePieces:['gown','robes','armor','costume','witch robes'], tops:['corset'], bottoms:['skirt'], poses:['standing powerfully','warrior pose','arms spread wide'], moods:['confident heroic mood','magical whimsical mood','regal majestic mood','fierce powerful mood'], occupations:['warrior','goddess','mage','witch','angel','princess','queen','sorceress'], clothingPresets:['Enchanted Grove Set','Fantasy Armor Set','Moonlit Sorceress Set'] },
  'movies':{ emoji:'🎬', name:'Cinematic', cameras:['cinematic portrait photography','film-inspired portrait photography','moody portrait photography','editorial fashion photography','high-fashion editorial photography'], props:['Film camera','Polaroid camera','Microphone','Candles','Mirror'], environments:['movie set','cyberpunk alley','futuristic city','ruins'], lighting:['dramatic lighting','neon city lights','dramatic sunset','colorful neon lights'], onePieces:['evening gown','catsuit','superhero suit','tactical suit'], tops:['jacket','coat'], bottoms:['jeans','cargo pants'], poses:['standing powerfully','looking over shoulder'], moods:['fierce powerful mood','bold daring mood','mysterious enchanting mood'], occupations:['superhero','actress'] },
  'nightlife':{ emoji:'🌃', name:'Nightlife', cameras:['moody portrait photography','glamour portrait photography','editorial fashion photography','high-fashion editorial photography','candid lifestyle photography','luxury campaign photography'], props:['Wine glass','Champagne glass','Microphone','Phone','Flowers'], environments:['rooftop bar','nightclub','concert hall'], lighting:['warm amber lighting','neon lights','colorful neon lights','chandelier glow'], onePieces:['cocktail dress','evening gown','bodycon dress','mini dress'], tops:['halter top','camisole'], bottoms:['skirt','dress pants'], poses:['standing elegantly','dancing'], moods:['elegant sophisticated mood','bold daring mood','energetic vibrant mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'historical':{ emoji:'🏛️', name:'Historical', cameras:['fine art portrait photography','film-inspired portrait photography','editorial fashion photography','environmental portrait photography','documentary lifestyle photography','vintage film photography'], props:['Scroll','Candles','Bouquet','Mirror','Book','Staff','Lantern','Rose'], environments:['museum','cathedral','palace','monastery'], lighting:['soft diffused light','candlelight','warm amber lighting'], onePieces:['gown','elegant dress','sari','kimono'], tops:['blouse'], bottoms:['skirt'], poses:['standing elegantly','seated elegantly'], moods:['elegant sophisticated mood','contemplative thoughtful mood','regal majestic mood'], occupations:['queen','princess'] },
  'travel':{ emoji:'🚗', name:'Travel', cameras:['travel editorial photography','documentary lifestyle photography','candid lifestyle photography','outdoor golden hour photography','storytelling lifestyle photography','aerial drone photography'], props:['Luggage','Suitcase','Map','Camera','Polaroid camera','Blanket'], environments:['airport','train station','harbor','boardwalk'], lighting:['natural daylight','bright natural sunlight'], onePieces:['jumpsuit','maxi dress','romper'], tops:['jacket','t-shirt','hoodie'], bottoms:['jeans','joggers','shorts'], poses:['walking confidently','strolling'], moods:['playful adventurous mood','joyful happy mood','carefree lighthearted mood'], occupations:['traveler','photographer'], clothingPresets:['Beach Lounge Set','Casual Coffee Run Set','Sunset Boardwalk Set','Travel Day Set'] },
  'dining':{ emoji:'🍽️', name:'Dining', cameras:['candid lifestyle photography','indoor natural light photography','soft natural light portrait photography','documentary lifestyle photography','editorial fashion photography'], props:['Wine glass','Tea cup','Champagne glass','Flowers','Single flower','Candles'], environments:['restaurant','cafe','winery','hotel lobby'], lighting:['candlelight','warm amber lighting','warm cafe lighting'], onePieces:['elegant dress','cocktail dress','midi dress','slip dress'], tops:['blouse','camisole'], bottoms:['dress pants','skirt'], poses:['seated elegantly','sitting comfortably'], moods:['romantic cozy mood','elegant sophisticated mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'events':{ emoji:'🎪', name:'Events', cameras:['editorial fashion photography','glamour portrait photography','commercial campaign photography','luxury campaign photography','high-fashion editorial photography','documentary lifestyle photography'], props:['Flowers','Bouquet','Champagne glass','Sparkler','Gift box','Trophy','Microphone','Balloons'], environments:['ballroom','concert hall','theater stage'], lighting:['chandelier glow','dramatic lighting','spotlights'], onePieces:['ball gown','evening gown','cocktail dress','elegant dress'], tops:['blazer','blouse'], bottoms:['dress pants','skirt'], poses:['celebrating','dancing','standing elegantly'], moods:['joyful happy mood','victorious triumphant mood','energetic vibrant mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'game-show':{ emoji:'🎰', name:'Game Show', cameras:['commercial campaign photography','glamour portrait photography','magazine cover photography','editorial fashion photography','cinematic portrait photography'], props:['Microphone','Trophy','Gift box','Sparkler','Balloons','Deck of cards','Champagne glass'], environments:['theater stage','concert hall','ballroom','dance studio'], lighting:['spotlights','bright overhead lighting','colorful neon lights','chandelier glow'], onePieces:['sequin dress','cocktail dress','evening gown','bodycon dress'], tops:['blazer','halter top'], bottoms:['skirt','dress pants'], poses:['standing confidently','arms spread wide','celebrating','standing with hand on hip'], moods:['joyful happy mood','energetic vibrant mood','victorious triumphant mood','glamorous dazzling mood','festive celebratory mood'], occupations:['host','actress','model'] },
  'mystery':{ emoji:'🔍', name:'Mystery & Noir', cameras:['cinematic portrait photography','film-inspired portrait photography','moody portrait photography','vintage film photography','fine art portrait photography'], props:['Film camera','Candles','Mirror','Envelope','Journal notebook','Map','Lantern','Umbrella'], environments:['rain-slicked street','cobblestone alley','underground speakeasy','victorian parlor','fog-covered moors','abandoned asylum','library'], lighting:['candlelight','dramatic low-key lighting','moody side lighting','single streetlamp glow','warm amber lighting','soft diffused light'], onePieces:['trench coat dress','pencil dress','vintage dress','silk slip dress'], tops:['blouse','camisole'], bottoms:['pencil skirt','midi skirt'], poses:['looking over shoulder','leaning against wall','seated contemplatively','standing confidently'], moods:['mysterious enchanting mood','contemplative thoughtful mood','bold daring mood','dramatic intense mood','noir brooding mood'], occupations:['detective','reporter','private investigator'] },
  'seasons':{ emoji:'🍂', name:'Seasons', cameras:['outdoor golden hour photography','environmental portrait photography','candid lifestyle photography','fine art portrait photography','storytelling lifestyle photography','documentary lifestyle photography'], props:['Flowers','Umbrella','Kite','Single flower','Bouquet','Watering can','Blanket'], environments:['spring meadow','summer garden','sunflower field','autumn forest','snowy landscape','winter wonderland','flower field','meadow'], lighting:['golden hour sunset','soft morning light','bright natural sunlight','overcast light'], onePieces:['sundress','maxi dress','wrap dress'], tops:['sweater','cardigan','coat'], bottoms:['jeans','leggings','skirt'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','carefree lighthearted mood','dreamy ethereal mood'], clothingPresets:['Boho Festival Set','Casual Coffee Run Set','Cozy At-Home Set'] },
  'flowers':{ emoji:'🌸', name:'Floral', cameras:['fine art portrait photography','romantic portrait photography','outdoor golden hour photography','soft natural light portrait photography','editorial fashion photography'], props:['Bouquet','Single flower','Flowers','Watering can','Basket of fruit','Parasol','Rose'], environments:['garden','botanical garden','flower field','lavender field','sunflower field','wildflower meadow'], lighting:['golden hour sunset','soft morning light','dappled sunlight through trees'], onePieces:['sundress','maxi dress','wrap dress','slip dress'], tops:['blouse','camisole'], bottoms:['skirt','shorts'], poses:['standing confidently','walking naturally','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','romantic cozy mood','dreamy ethereal mood'], clothingPresets:['Boho Festival Set','Sunset Boardwalk Set'] },
  'studio':{ emoji:'📸', name:'Studio', cameras:['studio portrait photography','studio beauty photography','beauty editorial photography','fine art portrait photography','glamour portrait photography','professional portrait photography','petite studio portrait photography','magazine cover photography'], props:['Mirror','Flowers','Bouquet','Candles','Single flower','Polaroid camera'], environments:['art studio','home studio'], lighting:['soft studio lighting','soft diffused light','dramatic lighting','ring light'], onePieces:['elegant dress','gown','maternity dress','slip dress'], tops:['camisole','bralette'], bottoms:['skirt','leggings'], poses:['standing confidently','cradling belly'], moods:['elegant sophisticated mood','confident heroic mood','dreamy ethereal mood'], clothingPresets:['Flowing Party Dress Set','Maternity Studio Set','Studio Glam Set'] },
  'wedding':{ emoji:'💍', name:'Wedding', cameras:['wedding portrait photography','romantic portrait photography','fine art portrait photography','outdoor golden hour photography','editorial fashion photography','soft natural light portrait photography'], props:['Bouquet','Flowers','Single flower','Rose','Champagne glass','Wine glass','Envelope'], environments:['ballroom','garden','cathedral','rose garden','botanical garden','vineyard','beach resort'], lighting:['chandelier glow','soft diffused light','golden hour sunset','divine golden light','fairy lights'], onePieces:['wedding dress','ball gown','slip dress','elegant dress','lace dress'], tops:['blouse','camisole'], bottoms:['skirt'], poses:['standing elegantly','holding flowers','twirling dress','seated elegantly'], moods:['romantic cozy mood','elegant sophisticated mood','joyful happy mood','dreamy ethereal mood','timeless classic mood'], occupations:['bride','model'], clothingPresets:['Wedding Day Set','Bridal Shower Set','Flowing Party Dress Set'] },
  'urban':{ emoji:'🏙️', name:'Urban', cameras:['street style photography','raw street style photography','candid lifestyle photography','editorial fashion photography','moody portrait photography','documentary lifestyle photography'], props:['Phone','Shopping bags','Coffee cup','Camera','Skateboard'], environments:['city street','graffiti wall','urban loft','rooftop bar','cobblestone alley','night market','neon arcade'], lighting:['neon signs','colorful neon lights','warm amber lighting','sunset city lights','dramatic stage light'], onePieces:['bodycon dress','little black dress','catsuit','leather jumpsuit'], tops:['crop top','halter top','camisole'], bottoms:['jeans','leather pants','high-waisted shorts','skater skirt'], poses:['leaning against wall','standing confidently','walking confidently','looking over shoulder'], moods:['bold daring mood','fierce powerful mood','mysterious enchanting mood','energetic vibrant mood'], occupations:['content creator','influencer','DJ','photographer'], clothingPresets:['Street Style Set','Urban Night Set','Date Night Dress Set'] },
  'autumn':{ emoji:'🍂', name:'Autumn', cameras:['outdoor golden hour photography','environmental portrait photography','documentary lifestyle photography','storytelling lifestyle photography','fine art portrait photography','vintage film photography','candid lifestyle photography'], props:['Umbrella','Candles','Kite','Blanket','Book','Coffee cup','Lantern','Flowers'], environments:['autumn forest','pumpkin patch','apple orchard','countryside','park','wheat field','covered bridge'], lighting:['golden hour sunset','warm amber lighting','overcast light','soft morning light'], onePieces:['maxi dress','sweater dress','midi dress','wrap dress'], tops:['flannel shirt','sweater','cardigan','turtleneck'], bottoms:['jeans','leggings','wide-leg pants','midi skirt'], poses:['walking naturally','standing confidently','picking flowers','throwing confetti'], moods:['carefree lighthearted mood','nostalgic reflective mood','peaceful serene mood','earthy grounded mood','cozy intimate mood'], clothingPresets:['Autumn Harvest Set','Fall Hiking Set','Cozy At-Home Set'] },
  'water-sports':{ emoji:'🏄', name:'Water Sports', cameras:['action sports photography','sports editorial photography','outdoor golden hour photography','travel editorial photography','candid lifestyle photography'], props:['Surfboard','Towel','Water bottle','Kite','Parasol','Umbrella'], environments:['beach','ocean','tropical beach','swimming pool','lake dock','waterfall','tropical island'], lighting:['bright natural sunlight','backlit sunset','blue water reflections','golden hour sunset'], onePieces:['one-piece swimsuit','swimdress','beach cover-up'], tops:['bikini top','rash guard','tankini top','sports bra'], bottoms:['bikini bottoms','board shorts','surf shorts','sarong'], poses:['surfing wave','floating in water','jumping mid-air','standing confidently'], moods:['energetic vibrant mood','carefree lighthearted mood','adventurous exploratory mood','healthy active mood'], clothingPresets:['Bikini Set','Pool Party Set','Resort Swim Set','Tropical Waterfall Set'] },
  'holiday':{ emoji:'🎄', name:'Holiday', cameras:['glamour portrait photography','editorial fashion photography','indoor natural light photography','commercial campaign photography','soft natural light portrait photography','luxury campaign photography'], props:['Gift box','Sparkler','Balloons','Candles','Champagne glass','Flowers','Teddy bear','Stuffed animal'], environments:['winter wonderland','cozy fireplace','snowy landscape','snowy cabin','ballroom'], lighting:['christmas lights','warm indoor lighting','candlelight','string lights','fairy lights'], onePieces:['sequin dress','velvet dress','ball gown','evening gown','velvet gown'], tops:['turtleneck','sweater'], bottoms:['leggings','skirt','dress pants'], poses:['standing elegantly','dancing','throwing confetti','holding flowers'], moods:['festive celebratory mood','joyful happy mood','magical whimsical mood','cozy intimate mood','glamorous dazzling mood'], clothingPresets:['Holiday Glam Set','Date Night Dress Set','Ski Lodge Set','Winter Coat Set'] }
};

// ==========================================
// STYLE_MODES — prompt style suffixes
// ==========================================
const STYLE_MODES = { 'Default':'', 'Cinematic':'cinematic, dramatic', 'Fantasy':'whimsical, fantastical', 'Romantic':'romantic, dreamy', 'Epic':'epic, grand', 'Documentary':'documentary, realistic' };

// ==========================================
// SEARCH_SYNONYMS — theme search expansion
// ==========================================
const SEARCH_SYNONYMS = {
  'sunset':['golden hour','dusk'], 'beach':['seaside','shore','coast','ocean','vacation'],
  'forest':['woods','jungle','nature','trees'], 'mountain':['alpine','peak','hiking'],
  'city':['urban','downtown','street'], 'snow':['snowy','winter','christmas'],
  'fantasy':['elf','fairy','dragon','enchanted','magic'], 'gym':['fitness','workout','yoga'],
  'art':['creative','studio','gallery','paint'], 'food':['dining','restaurant','cafe','coffee'],
  'wedding':['bridal','bride','marriage','ceremony'], 'autumn':['fall','harvest','leaves','pumpkin'],
  'party':['holiday','celebration','festive','events'], 'swim':['pool','water','surfing','ocean'],
  'street':['urban','graffiti','city','downtown']
};
