// ==========================================
// THEMES (with aligned clothing values)
// ==========================================
const THEMES = {
  'at-home':{ emoji:'🏠', name:'At Home', cameras:['soft natural light portrait photography','indoor natural light photography','candid lifestyle photography','documentary lifestyle photography','boudoir portrait photography','family portrait photography','romantic portrait photography'], props:['Coffee cup','Book','Pillow','Blanket','Candles','Tea cup','Journal notebook','Phone','Fairy lights','Stuffed animal','Teddy bear'], environments:['modern living room','cozy bedroom'], lighting:['warm window light','soft morning light','warm lamp light'], onePieces:['robe','nightgown','maxi dress'], tops:['sweater','hoodie','t-shirt'], bottoms:['leggings','joggers','yoga pants'], poses:['sitting comfortably','relaxed pose','lounging'], moods:['peaceful content mood','relaxed comfortable mood'], clothingPresets:['Cozy At-Home Set','Casual Coffee Run Set'] },
  'at-office':{ emoji:'💼', name:'Office', cameras:['professional portrait photography','commercial campaign photography','environmental portrait photography','documentary lifestyle photography','editorial fashion photography','high-end lifestyle photography'], props:['Laptop','Briefcase','Phone','Book','Coffee cup','Journal notebook'], environments:['office','conference room'], lighting:['bright overhead lighting','soft professional lighting'], onePieces:['A-line dress','shift dress','jumpsuit'], tops:['blazer','blouse','shirt'], bottoms:['dress pants','skirt'], poses:['standing confidently','professional pose'], moods:['confident heroic mood','elegant sophisticated mood'], occupations:['businesswoman','lawyer','architect'], clothingPresets:['Classic Office Set','Smart Casual Office Set'] },
  'on-vacation':{ emoji:'🏖️', name:'Vacation', cameras:['travel editorial photography','outdoor golden hour photography','candid lifestyle photography','high-end lifestyle photography','storytelling lifestyle photography','fashion catalog photography'], props:['Camera','Map','Luggage','Parasol','Flowers','Fruit bowl','Polaroid camera'], environments:['tropical beach','beach resort','ocean','cruise ship deck'], lighting:['golden hour sunset','bright natural sunlight','blue water reflections'], onePieces:['sundress','beach dress','maxi dress','swim cover-up','one-piece swimsuit'], tops:['tank top','camisole','bikini top','tankini top'], bottoms:['shorts','skirt','bikini bottoms','sarong'], poses:['standing confidently','walking naturally','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','happy relaxed mood'], clothingPresets:['Beach Cover-Up Set','Beach Lounge Set','Bikini Set','Resort Swim Set','Sunset Boardwalk Set'] },
  'beach-day':{ emoji:'🌊', name:'Beach Day', cameras:['outdoor golden hour photography','travel editorial photography','candid lifestyle photography','fashion catalog photography','action sports photography','sports editorial photography'], props:['Surfboard','Towel','Parasol','Ice cream cone','Flowers','Kite','Bubbles'], environments:['beach','boardwalk','ocean','tropical beach'], lighting:['backlit sunset','bright natural sunlight','golden hour sunset'], onePieces:['beach cover-up','one-piece swimsuit','swim cover-up'], tops:['bikini top','tankini top','triangle bikini top'], bottoms:['bikini bottoms','sarong','swim skirt'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['carefree lighthearted mood','joyful happy mood','happy relaxed mood'], clothingPresets:['Beach Cover-Up Set','Bikini Set','Resort Swim Set','Sunset Boardwalk Set'] },
  'prehistoric-jungle':{ emoji:'🦖', name:'Prehistoric / Jungle', cameras:['environmental portrait photography','documentary lifestyle photography','cinematic portrait photography','film-inspired portrait photography','storytelling lifestyle photography'], props:['Map','Lantern','Staff','Scroll','Artifact','Camp lantern'], environments:['dense jungle','jungle river','jungle ruins','prehistoric fern valley','rainforest waterfall','tropical jungle clearing','volcanic ridge'], lighting:['dappled sunlight through trees','golden hour sunset','humid misty light','soft diffused light'], onePieces:['explorer romper','survival wrap dress','utility jumpsuit'], tops:['linen shirt','mesh cover-up top','peasant blouse','tribal halter top','utility vest'], bottoms:['cargo pants','sarong','survival skirt','tailored shorts','utility shorts'], poses:['crouching slightly','standing confidently','strolling','walking naturally'], moods:['bold daring mood','fierce powerful mood','playful adventurous mood','wild untamed mood'], occupations:['adventurer','archaeologist','explorer','survivalist'], clothingPresets:['Explorer Jungle Set','Jungle Adventure Set','Prehistoric Huntress Set','Safari Linen Set','Tropical Waterfall Set'] },
  'coffee-cafes':{ emoji:'☕', name:'Coffee & Cafes', cameras:['candid lifestyle photography','indoor natural light photography','soft natural light portrait photography','documentary lifestyle photography','storytelling lifestyle photography'], props:['Coffee cup','Book','Journal notebook','Tea cup','Phone','Flowers','Single flower'], environments:['cafe','coffee shop','bookstore'], lighting:['warm cafe lighting','warm window light','natural daylight'], onePieces:['sundress','wrap dress','midi dress'], tops:['sweater','cardigan','blouse'], bottoms:['jeans','skirt','leggings'], poses:['sitting comfortably','relaxed pose'], moods:['peaceful content mood','relaxed comfortable mood'], clothingPresets:['Casual Coffee Run Set'] },
  'fitness':{ emoji:'🏋️', name:'Fitness', cameras:['action sports photography','sports editorial photography','documentary lifestyle photography','candid lifestyle photography','commercial campaign photography'], props:['Dumbbells','Yoga mat','Jump rope','Water bottle','Smoothie cup','Soccer ball','Tennis racket'], environments:['gym','yoga studio','spa'], lighting:['bright gym lighting','soft natural light'], onePieces:['bodysuit'], tops:['sports bra','tank top'], bottoms:['leggings','yoga pants','bike shorts'], poses:['yoga pose','stretching','standing confidently','warrior pose'], moods:['energetic vibrant mood','healthy active mood','fierce powerful mood'], clothingPresets:['Fitness Training Set'] },
  'nature':{ emoji:'🌲', name:'Nature', cameras:['outdoor golden hour photography','environmental portrait photography','storytelling lifestyle photography','documentary lifestyle photography','fine art portrait photography','aerial drone photography'], props:['Flowers','Watering can','Bouquet','Single flower','Kite','Umbrella','Picnic basket','Basket of fruit'], environments:['forest','flower field','mountain trail with pine trees','garden','meadow','lavender field'], lighting:['golden hour sunset','soft morning light','dappled sunlight through trees'], onePieces:['sundress','maxi dress'], tops:['t-shirt','cardigan'], bottoms:['jeans','shorts'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['peaceful serene mood','joyful happy mood','calm tranquil mood'], clothingPresets:['Boho Festival Set','Explorer Jungle Set','Safari Linen Set','Sunset Boardwalk Set'] },
  'creative':{ emoji:'🎭', name:'Creative', cameras:['fine art portrait photography','editorial fashion photography','film-inspired portrait photography','moody portrait photography','studio beauty photography','runway backstage photography'], props:['Paint palette','Sketchbook','Guitar','Violin','Acoustic guitar','Canvas painting','Film camera','Microphone','Pottery wheel','Musical instrument'], environments:['art studio','theater stage','art gallery','dance studio'], lighting:['soft studio lighting','stage lighting','warm lamp light'], onePieces:['wrap dress','jumpsuit','kimono'], tops:['blouse','crop top'], bottoms:['wide-leg pants','skirt'], poses:['standing confidently','dancing'], moods:['passionate intense mood','bold daring mood','dreamy ethereal mood'], occupations:['artist','dancer','musician','painter'], clothingPresets:['Boho Festival Set','Flowing Party Dress Set'] },
  'shopping':{ emoji:'🛍️', name:'Shopping', cameras:['editorial fashion photography','fashion catalog photography','street style photography','commercial campaign photography','high-end lifestyle photography','candid lifestyle photography'], props:['Shopping bags','Designer shopping bags','Purse','Phone','Coffee cup'], environments:['boutique','urban street','hotel lobby'], lighting:['natural daylight','bright overhead lighting'], onePieces:['midi dress','cocktail dress','A-line dress'], tops:['blazer','blouse','cardigan'], bottoms:['jeans','skirt','dress pants'], poses:['walking confidently','standing with hand on hip'], moods:['joyful happy mood','confident heroic mood','playful adventurous mood'], clothingPresets:['Casual Coffee Run Set','Smart Casual Office Set','Sunset Boardwalk Set'] },
  'fantasy':{ emoji:'🧚', name:'Fantasy', cameras:['cinematic portrait photography','fine art portrait photography','film-inspired portrait photography','moody portrait photography','editorial fashion photography'], props:['Staff','Scroll','Shield','Crystal ball','Lantern','Dreamcatcher','Candles','Flowers'], environments:['enchanted forest','gothic castle','medieval castle','throne room'], lighting:['magical glow','dramatic lighting','divine golden light','purple magical energy'], onePieces:['gown','robes','armor','costume','witch robes'], tops:['corset'], bottoms:['skirt'], poses:['standing powerfully','warrior pose','arms spread wide'], moods:['confident heroic mood','magical whimsical mood','regal majestic mood','fierce powerful mood'], occupations:['warrior','goddess','mage','witch','angel','princess','queen','sorceress'], clothingPresets:['Enchanted Grove Set','Fantasy Armor Set','Moonlit Sorceress Set'] },
  'movies':{ emoji:'🎬', name:'Cinematic', cameras:['cinematic portrait photography','film-inspired portrait photography','moody portrait photography','editorial fashion photography','high-fashion editorial photography'], props:['Film camera','Polaroid camera','Microphone','Candles','Mirror'], environments:['movie set','cyberpunk alley','futuristic city','ruins'], lighting:['dramatic lighting','neon city lights','dramatic sunset','colorful neon lights'], onePieces:['evening gown','catsuit','superhero suit','tactical suit'], tops:['jacket','coat'], bottoms:['jeans','cargo pants'], poses:['standing powerfully','looking over shoulder'], moods:['fierce powerful mood','bold daring mood','mysterious enchanting mood'], occupations:['superhero','actress'] },
  'nightlife':{ emoji:'🌃', name:'Nightlife', cameras:['moody portrait photography','glamour portrait photography','editorial fashion photography','high-fashion editorial photography','candid lifestyle photography','luxury campaign photography'], props:['Wine glass','Champagne glass','Microphone','Phone','Flowers'], environments:['rooftop bar','nightclub','concert hall'], lighting:['warm amber lighting','neon lights','colorful neon lights','chandelier glow'], onePieces:['cocktail dress','evening gown','bodycon dress','mini dress'], tops:['halter top','camisole'], bottoms:['skirt','dress pants'], poses:['standing elegantly','dancing'], moods:['elegant sophisticated mood','bold daring mood','energetic vibrant mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'historical':{ emoji:'🏛️', name:'Historical', cameras:['fine art portrait photography','film-inspired portrait photography','editorial fashion photography','environmental portrait photography','documentary lifestyle photography','vintage film photography'], props:['Scroll','Candles','Bouquet','Mirror','Book','Staff','Lantern','Rose'], environments:['museum','cathedral','palace','monastery'], lighting:['soft diffused light','candlelight','warm amber lighting'], onePieces:['gown','elegant dress','sari','kimono'], tops:['blouse'], bottoms:['skirt'], poses:['standing elegantly','seated elegantly'], moods:['elegant sophisticated mood','contemplative thoughtful mood','regal majestic mood'], occupations:['queen','princess'] },
  'travel':{ emoji:'🚗', name:'Travel', cameras:['travel editorial photography','documentary lifestyle photography','candid lifestyle photography','outdoor golden hour photography','storytelling lifestyle photography','aerial drone photography'], props:['Luggage','Suitcase','Map','Camera','Polaroid camera','Blanket'], environments:['airport','train station','harbor','boardwalk'], lighting:['natural daylight','bright natural sunlight'], onePieces:['jumpsuit','maxi dress','romper'], tops:['jacket','t-shirt','hoodie'], bottoms:['jeans','joggers','shorts'], poses:['walking confidently','strolling'], moods:['playful adventurous mood','joyful happy mood','carefree lighthearted mood'], occupations:['traveler','photographer'], clothingPresets:['Beach Lounge Set','Casual Coffee Run Set','Sunset Boardwalk Set','Travel Day Set'] },
  'dining':{ emoji:'🍽️', name:'Dining', cameras:['candid lifestyle photography','indoor natural light photography','soft natural light portrait photography','documentary lifestyle photography','editorial fashion photography'], props:['Wine glass','Tea cup','Champagne glass','Flowers','Single flower','Candles'], environments:['restaurant','cafe','winery','hotel lobby'], lighting:['candlelight','warm amber lighting','warm cafe lighting'], onePieces:['elegant dress','cocktail dress','midi dress','slip dress'], tops:['blouse','camisole'], bottoms:['dress pants','skirt'], poses:['seated elegantly','sitting comfortably'], moods:['romantic cozy mood','elegant sophisticated mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'events':{ emoji:'🎪', name:'Events', cameras:['editorial fashion photography','glamour portrait photography','commercial campaign photography','luxury campaign photography','high-fashion editorial photography','documentary lifestyle photography'], props:['Flowers','Bouquet','Champagne glass','Sparkler','Gift box','Trophy','Microphone','Balloons'], environments:['ballroom','concert hall','theater stage'], lighting:['chandelier glow','dramatic lighting','spotlights'], onePieces:['ball gown','evening gown','cocktail dress','elegant dress'], tops:['blazer','blouse'], bottoms:['dress pants','skirt'], poses:['celebrating','dancing','standing elegantly'], moods:['joyful happy mood','victorious triumphant mood','energetic vibrant mood'], clothingPresets:['Date Night Dress Set','Flowing Party Dress Set'] },
  'game-show':{ emoji:'🎰', name:'Game Show', cameras:['commercial campaign photography','glamour portrait photography','magazine cover photography','editorial fashion photography','cinematic portrait photography'], props:['Microphone','Trophy','Gift box','Sparkler','Balloons','Deck of cards','Champagne glass'], environments:['theater stage','concert hall','ballroom','dance studio'], lighting:['spotlights','bright overhead lighting','colorful neon lights','chandelier glow'], onePieces:['sequin dress','cocktail dress','evening gown','bodycon dress'], tops:['blazer','halter top'], bottoms:['skirt','dress pants'], poses:['standing confidently','arms spread wide','celebrating','standing with hand on hip'], moods:['joyful happy mood','energetic vibrant mood','victorious triumphant mood','glamorous dazzling mood','festive celebratory mood'], occupations:['host','actress','model'] },
  'mystery':{ emoji:'🔍', name:'Mystery & Noir', cameras:['cinematic portrait photography','film-inspired portrait photography','moody portrait photography','vintage film photography','fine art portrait photography'], props:['Film camera','Candles','Mirror','Envelope','Journal notebook','Map','Lantern','Umbrella'], environments:['rain-slicked street','cobblestone alley','underground speakeasy','victorian parlor','fog-covered moors','abandoned asylum','library'], lighting:['candlelight','dramatic low-key lighting','moody side lighting','single streetlamp glow','warm amber lighting','soft diffused light'], onePieces:['trench coat dress','pencil dress','vintage dress','silk slip dress'], tops:['blouse','camisole'], bottoms:['pencil skirt','midi skirt'], poses:['looking over shoulder','leaning against wall','seated contemplatively','standing confidently'], moods:['mysterious enchanting mood','contemplative thoughtful mood','bold daring mood','dramatic intense mood','noir brooding mood'], occupations:['detective','reporter','private investigator'] },
  'seasons':{ emoji:'🍂', name:'Seasons', cameras:['outdoor golden hour photography','environmental portrait photography','candid lifestyle photography','fine art portrait photography','storytelling lifestyle photography','documentary lifestyle photography'], props:['Flowers','Umbrella','Kite','Single flower','Bouquet','Watering can','Blanket'], environments:['spring meadow','summer garden','sunflower field','autumn forest','snowy landscape','winter wonderland','flower field','meadow'], lighting:['golden hour sunset','soft morning light','bright natural sunlight','overcast light'], onePieces:['sundress','maxi dress','wrap dress'], tops:['sweater','cardigan','coat'], bottoms:['jeans','leggings','skirt'], poses:['walking naturally','standing confidently','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','carefree lighthearted mood','dreamy ethereal mood'], clothingPresets:['Boho Festival Set','Casual Coffee Run Set','Cozy At-Home Set'] },
  'flowers':{ emoji:'🌸', name:'Floral', cameras:['fine art portrait photography','romantic portrait photography','outdoor golden hour photography','soft natural light portrait photography','editorial fashion photography'], props:['Bouquet','Single flower','Flowers','Watering can','Basket of fruit','Parasol','Rose'], environments:['garden','botanical garden','flower field','lavender field','sunflower field','wildflower meadow'], lighting:['golden hour sunset','soft morning light','dappled sunlight through trees'], onePieces:['sundress','maxi dress','wrap dress','slip dress'], tops:['blouse','camisole'], bottoms:['skirt','shorts'], poses:['standing confidently','walking naturally','relaxed pose'], moods:['joyful happy mood','peaceful serene mood','romantic cozy mood','dreamy ethereal mood'], clothingPresets:['Boho Festival Set','Sunset Boardwalk Set'] },
  'studio':{ emoji:'📸', name:'Studio', cameras:['studio portrait photography','studio beauty photography','beauty editorial photography','fine art portrait photography','glamour portrait photography','professional portrait photography','petite studio portrait photography','magazine cover photography'], props:['Mirror','Flowers','Bouquet','Candles','Single flower','Polaroid camera'], environments:['art studio','home studio'], lighting:['soft studio lighting','soft diffused light','dramatic lighting','ring light'], onePieces:['elegant dress','gown','maternity dress','slip dress'], tops:['camisole','bralette'], bottoms:['skirt','leggings'], poses:['standing confidently','cradling belly'], moods:['elegant sophisticated mood','confident heroic mood','dreamy ethereal mood'], clothingPresets:['Flowing Party Dress Set','Maternity Studio Set','Studio Glam Set'] },
  'wedding':{ emoji:'💍', name:'Wedding', cameras:['wedding portrait photography','romantic portrait photography','fine art portrait photography','outdoor golden hour photography','editorial fashion photography','soft natural light portrait photography'], props:['Bouquet','Flowers','Single flower','Rose','Champagne glass','Wine glass','Envelope'], environments:['ballroom','garden','cathedral','rose garden','botanical garden','vineyard','beach resort'], lighting:['chandelier glow','soft diffused light','golden hour sunset','divine golden light','fairy lights'], onePieces:['wedding dress','ball gown','slip dress','elegant dress','lace dress'], tops:['blouse','camisole'], bottoms:['skirt'], poses:['standing elegantly','holding flowers','twirling dress','seated elegantly'], moods:['romantic cozy mood','elegant sophisticated mood','joyful happy mood','dreamy ethereal mood','timeless classic mood'], occupations:['bride','model'], clothingPresets:['Wedding Day Set','Bridal Shower Set','Flowing Party Dress Set'] },
  'urban':{ emoji:'🏙️', name:'Urban', cameras:['street style photography','raw street style photography','candid lifestyle photography','editorial fashion photography','moody portrait photography','documentary lifestyle photography'], props:['Phone','Shopping bags','Coffee cup','Camera','Skateboard'], environments:['city street','graffiti wall','urban loft','rooftop bar','cobblestone alley','night market','neon arcade'], lighting:['neon signs','colorful neon lights','warm amber lighting','sunset city lights','dramatic stage light'], onePieces:['bodycon dress','little black dress','catsuit','leather jumpsuit'], tops:['crop top','halter top','camisole'], bottoms:['jeans','leather pants','high-waisted shorts','skater skirt'], poses:['leaning against wall','standing confidently','walking confidently','looking over shoulder'], moods:['bold daring mood','fierce powerful mood','mysterious enchanting mood','energetic vibrant mood'], occupations:['content creator','influencer','DJ','photographer'], clothingPresets:['Street Style Set','Urban Night Set','Date Night Dress Set'] },
  'autumn':{ emoji:'🍂', name:'Autumn', cameras:['outdoor golden hour photography','environmental portrait photography','documentary lifestyle photography','storytelling lifestyle photography','fine art portrait photography','vintage film photography','candid lifestyle photography'], props:['Umbrella','Candles','Kite','Blanket','Book','Coffee cup','Lantern','Flowers'], environments:['autumn forest','pumpkin patch','apple orchard','countryside','park','wheat field','covered bridge'], lighting:['golden hour sunset','warm amber lighting','overcast light','soft morning light'], onePieces:['maxi dress','sweater dress','midi dress','wrap dress'], tops:['flannel shirt','sweater','cardigan','turtleneck'], bottoms:['jeans','leggings','wide-leg pants','midi skirt'], poses:['walking naturally','standing confidently','picking flowers','throwing confetti'], moods:['carefree lighthearted mood','nostalgic reflective mood','peaceful serene mood','earthy grounded mood','cozy intimate mood'], clothingPresets:['Autumn Harvest Set','Fall Hiking Set','Cozy At-Home Set'] },
  'water-sports':{ emoji:'🏄', name:'Water Sports', cameras:['action sports photography','sports editorial photography','outdoor golden hour photography','travel editorial photography','candid lifestyle photography'], props:['Surfboard','Towel','Water bottle','Kite','Parasol','Umbrella'], environments:['beach','ocean','tropical beach','swimming pool','lake dock','waterfall','tropical island'], lighting:['bright natural sunlight','backlit sunset','blue water reflections','golden hour sunset'], onePieces:['one-piece swimsuit','swimdress','beach cover-up'], tops:['bikini top','rash guard','tankini top','sports bra'], bottoms:['bikini bottoms','board shorts','surf shorts','sarong'], poses:['surfing wave','floating in water','jumping mid-air','standing confidently'], moods:['energetic vibrant mood','carefree lighthearted mood','adventurous exploratory mood','healthy active mood'], clothingPresets:['Bikini Set','Pool Party Set','Resort Swim Set','Tropical Waterfall Set'] },
  'holiday':{ emoji:'🎄', name:'Holiday', cameras:['glamour portrait photography','editorial fashion photography','indoor natural light photography','commercial campaign photography','soft natural light portrait photography','luxury campaign photography'], props:['Gift box','Sparkler','Balloons','Candles','Champagne glass','Flowers','Teddy bear','Stuffed animal'], environments:['winter wonderland','cozy fireplace','snowy landscape','snowy cabin','ballroom'], lighting:['christmas lights','warm indoor lighting','candlelight','string lights','fairy lights'], onePieces:['sequin dress','velvet dress','ball gown','evening gown','velvet gown'], tops:['turtleneck','sweater'], bottoms:['leggings','skirt','dress pants'], poses:['standing elegantly','dancing','throwing confetti','holding flowers'], moods:['festive celebratory mood','joyful happy mood','magical whimsical mood','cozy intimate mood','glamorous dazzling mood'], clothingPresets:['Holiday Glam Set','Date Night Dress Set','Ski Lodge Set','Winter Coat Set'] },
  'steampunk':{ emoji:'⚙️', name:'Steampunk', cameras:['cinematic portrait photography','film-inspired portrait photography','vintage film photography','editorial fashion photography','environmental portrait photography'], props:['Pocket watch','Compass','Telescope','Hourglass','Binoculars','Lantern','Artifact'], environments:['Steampunk airship dock','Victorian clockwork factory','Steam-powered city','Brass workshop'], lighting:['Warm amber lighting','Candlelit dungeon','Foggy lantern glow','Edison bulbs','Flickering torchlight'], onePieces:['corset dress','Victorian gown','leather jumpsuit'], tops:['corset','blouse','vest'], bottoms:['high-waisted shorts','dress pants','skirt'], poses:['standing confidently','looking over shoulder','arms crossed'], moods:['bold daring mood','mysterious enchanting mood','elegant sophisticated mood','adventurous exploratory mood'], occupations:['engineer','pilot','mechanic','architect'], clothingPresets:['Steampunk Explorer Set'] },
  'cyberpunk':{ emoji:'🤖', name:'Cyberpunk', cameras:['cinematic portrait photography','moody portrait photography','editorial fashion photography','raw street style photography','street style photography'], props:['Laptop','Phone','Headphones','Binoculars'], environments:['Cyberpunk nightclub','Holographic plaza','Neon corridor','Underground hacker den','Cyberpunk alley','Futuristic city'], lighting:['Cyberpunk neon','Cyberpunk hologram light','Colorful neon lights','Neon signs','Laser beams','Electric storm glow'], onePieces:['catsuit','bodysuit','cyberpunk techwear','leather jumpsuit'], tops:['crop top','halter top'], bottoms:['leather pants','bike shorts'], poses:['standing confidently','looking over shoulder','leaning against wall'], moods:['bold daring mood','fierce powerful mood','mysterious enchanting mood','dark brooding mood'], occupations:['cyberpunk hacker','mechanic','DJ','engineer'], clothingPresets:['Cyberpunk Street Set'] },
  'gothic':{ emoji:'🦇', name:'Gothic', cameras:['moody portrait photography','cinematic portrait photography','fine art portrait photography','film-inspired portrait photography','vintage film photography'], props:['Candles','Crystal ball','Scroll','Lantern','Staff','Rose','Mirror'], environments:['Gothic cathedral ruins','Haunted mansion','Cemetery at midnight','Catacombs','Gothic castle'], lighting:['Candlelight','Flickering torchlight','Dramatic side lighting','Magical energy','Foggy atmosphere'], onePieces:['Gothic dress','Gown','Corset dress','Velvet dress'], tops:['corset','blouse'], bottoms:['maxi skirt','midi skirt'], poses:['standing elegantly','looking over shoulder','arms spread wide'], moods:['mysterious enchanting mood','dark brooding mood','passionate intense mood','ethereal otherworldly mood'], occupations:['witch','vampire hunter','mage','priestess'], clothingPresets:['Gothic Romance Set','Moonlit Sorceress Set'] },
  'western':{ emoji:'🤠', name:'Western', cameras:['documentary lifestyle photography','cinematic portrait photography','environmental portrait photography','travel editorial photography','vintage film photography'], props:['Compass','Rope','Lantern','Map','Acoustic guitar'], environments:['Wild West saloon','Frontier town','Desert canyon at sunset','Gold rush mine','Ranch','Desert dunes'], lighting:['Golden hour sunset','Warm amber lighting','Campfire glow','Desert midday sun','Dramatic sunset'], onePieces:['Duster coat dress'], tops:['flannel shirt','blouse','vest'], bottoms:['jeans','high-waisted shorts','skirt'], poses:['standing confidently','leaning against wall','relaxed pose'], moods:['bold daring mood','adventurous exploratory mood','earthy grounded mood','fierce powerful mood'], occupations:['cowgirl','explorer','adventurer','sheriff'], clothingPresets:['Western Cowgirl Set'] },
  'mythology':{ emoji:'⚡', name:'Mythology', cameras:['cinematic portrait photography','fine art portrait photography','editorial fashion photography','film-inspired portrait photography'], props:['Staff','Shield','Scroll','Artifact','Horn','Flowers'], environments:['Mount Olympus','Ancient Greek temple','Egyptian pyramid chamber','Norse longhouse','Ancient temple ruins','Palace','Throne room'], lighting:['Divine golden light','Dramatic stage light','Magical energy','Golden hour sunset','Cosmic glow'], onePieces:['Gown','Toga','Armor','Sari'], tops:['corset','blouse'], bottoms:['skirt','maxi skirt'], poses:['standing powerfully','arms spread wide','warrior pose'], moods:['confident heroic mood','powerful bold mood','ethereal otherworldly mood','timeless classic mood'], occupations:['goddess','oracle','priestess','warrior','valkyrie','siren'], clothingPresets:['Greek Goddess Set','Fantasy Armor Set'] },
  'superhero':{ emoji:'🦸', name:'Superhero', cameras:['cinematic portrait photography','action sports photography','commercial campaign photography','editorial fashion photography'], props:['Shield','Binoculars','Trophy','Staff'], environments:['Destroyed cityscape','Secret underground lair','City rooftop','Futuristic city','City street'], lighting:['Dramatic side lighting','Lightning storm','Spotlights','Dramatic sunset','Cosmic glow'], onePieces:['superhero suit','armor','catsuit','bodysuit'], tops:['jacket','vest'], bottoms:['leggings','bike shorts'], poses:['standing powerfully','arms spread wide','jumping mid-air'], moods:['confident heroic mood','fierce powerful mood','bold daring mood','victorious triumphant mood'], occupations:['superhero','soldier','warrior'], clothingPresets:['Superhero Cape Set'] },
  'pirate':{ emoji:'☠️', name:'Pirate', cameras:['cinematic portrait photography','film-inspired portrait photography','documentary lifestyle photography','travel editorial photography','environmental portrait photography'], props:['Map','Compass','Treasure chest','Rope','Lantern','Binoculars','Horn','Scroll'], environments:['Pirate ship deck','Caribbean cove','Treasure island','Sunken shipwreck','Harbor','Lighthouse'], lighting:['Golden hour sunset','Dramatic sunset','Backlit sunset','Campfire glow','Dramatic storm lighting'], onePieces:['costume','Corset dress','Cover-up dress'], tops:['blouse','vest','shirt'], bottoms:['cargo pants','high-waisted shorts','skirt','sarong'], poses:['standing confidently','relaxed pose','looking over shoulder'], moods:['bold daring mood','adventurous exploratory mood','fierce powerful mood','carefree lighthearted mood'], occupations:['pirate captain','sailor','adventurer','explorer'], clothingPresets:['Pirate Queen Set'] },
  'viking':{ emoji:'⚔️', name:'Viking', cameras:['cinematic portrait photography','environmental portrait photography','documentary lifestyle photography','film-inspired portrait photography','vintage film photography'], props:['Shield','Sword','Horn','Staff','Rope','Lantern','Map'], environments:['Viking longhouse','Nordic fjord','Norse village','Norse longhouse','Mountains','Tundra'], lighting:['Campfire glow','Golden hour sunset','Dramatic storm lighting','Overcast light','Flickering torchlight'], onePieces:['armor','gown','costume'], tops:['vest','blouse','shirt'], bottoms:['skirt','cargo pants','maxi skirt'], poses:['standing powerfully','arms crossed','warrior pose'], moods:['fierce powerful mood','bold daring mood','wild untamed mood','adventurous exploratory mood'], occupations:['warrior','valkyrie','adventurer','mercenary'], clothingPresets:['Viking Shield Maiden Set'] },
  'cottagecore':{ emoji:'🌿', name:'Cottagecore', cameras:['soft natural light portrait photography','outdoor golden hour photography','candid lifestyle photography','romantic portrait photography','fine art portrait photography'], props:['Flowers','Bouquet','Single flower','Watering can','Basket of fruit','Tea cup','Book','Blanket'], environments:['Wildflower cottage','Mushroom grove','Cozy country kitchen','Flower field','Garden','Botanical garden','Countryside','Backyard garden'], lighting:['Soft morning light','Warm window light','Golden hour sunset','Dappled sunlight','Warm lamp light'], onePieces:['sundress','maxi dress','midi dress','wrap dress','apron dress'], tops:['blouse','cardigan','camisole'], bottoms:['skirt','maxi skirt','shorts'], poses:['picking flowers','gardening','sitting comfortably','walking naturally'], moods:['peaceful serene mood','romantic cozy mood','earthy grounded mood','soft whimsical mood','joyful happy mood'], occupations:['florist','farmer','botanist','baker'], clothingPresets:['Cottagecore Garden Set'] },
  'scifi':{ emoji:'🚀', name:'Sci-Fi', cameras:['cinematic portrait photography','commercial campaign photography','editorial fashion photography','film-inspired portrait photography'], props:['Laptop','Phone','Artifact','Telescope','Binoculars','Compass'], environments:['Space station','Mars colony','Futuristic city','Floating sky castle','Holographic plaza','Neon corridor','Laboratory','Astronomy observatory'], lighting:['Galaxy glow','Cosmic glow','Holographic signs','Laser beams','Cyberpunk neon','Electric storm glow'], onePieces:['space suit','cyberpunk techwear','catsuit','jumpsuit','bodysuit'], tops:['vest','jacket'], bottoms:['leggings','bike shorts','cargo pants'], poses:['standing confidently','looking away thoughtfully','arms spread wide'], moods:['adventurous exploratory mood','bold daring mood','ethereal otherworldly mood','fierce powerful mood'], occupations:['astronaut','scientist','researcher','engineer'], clothingPresets:['Sci-Fi Commander Set'] },
  'dark-academia':{ emoji:'📚', name:'Dark Academia', cameras:['fine art portrait photography','vintage film photography','moody portrait photography','film-inspired portrait photography','editorial fashion photography'], props:['Book','Journal notebook','Quill pen','Ancient tome','Candles','Hourglass','Map','Envelope'], environments:['Gothic university hallway','Old stone library','Candlelit study room','Library','Museum','Cathedral','Ancient library'], lighting:['Candlelight','Warm lamp light','Warm amber lighting','Overcast light','Soft diffused light'], onePieces:['pencil dress','midi dress','knitted dress'], tops:['blazer','turtleneck','blouse','cardigan'], bottoms:['wide-leg pants','dress pants','skirt'], poses:['reading book','writing in journal','seated elegantly','standing elegantly'], moods:['introspective quiet mood','melancholic wistful mood','mysterious enchanting mood','elegant sophisticated mood','nostalgic reflective mood'], occupations:['professor','librarian','writer','researcher'], clothingPresets:['Dark Academia Set'] },
  'anime':{ emoji:'🌸', name:'Anime', cameras:['fine art portrait photography','editorial fashion photography','studio beauty photography','beauty editorial photography','cinematic portrait photography'], props:['Single flower','Flowers','Wand','Crystal ball','Umbrella','Bouquet','Parasol'], environments:['Cherry blossom shrine','Floating sky castle','Anime city street','Ancient spirit forest','Cherry blossom garden','Cherry blossom park','Japanese tea house','Zen garden'], lighting:['Anime-style light beams','Soft morning light','Magical energy','Golden hour sunset','Bioluminescent glow'], onePieces:['kimono','bodysuit','uniform','costume','cosplay outfit'], tops:['blouse','camisole','cardigan'], bottoms:['mini skirt','skater skirt','skirt'], poses:['standing elegantly','overhead stretch','relaxed pose','waving'], moods:['joyful happy mood','dreamy ethereal mood','magical whimsical mood','cheerful bubbly mood','soft whimsical mood'], occupations:['dancer','singer','model','artist'], clothingPresets:['Anime Style Set'] },
  'world-explorer':{ emoji:'🌍', name:'World Explorer', cameras:['travel editorial photography','documentary lifestyle photography','environmental portrait photography','outdoor golden hour photography','storytelling lifestyle photography','candid lifestyle photography','aerial drone photography'], props:['Camera','Map','Compass','Luggage','Suitcase','Polaroid camera','Journal notebook','Binoculars','Telescope','Water bottle'], environments:['Bali rice terrace','Santorini cliffside sunset','Machu Picchu sunrise','Tokyo Shibuya crossing','Venice canal gondola','Moroccan desert camp','Norwegian fjord village','Great Wall of China overlook','Havana colorful street','African savanna sunset','Amsterdam canal bridge','Petra canyon entrance','New Zealand mountain valley','Vietnamese lantern street','Scottish highlands'], lighting:['Golden hour sunset','Bright natural sunlight','Soft morning light','Natural daylight','Dramatic sunset','Dawn light','Warm amber lighting','Sunset through clouds'], onePieces:['Sundress','Maxi dress','Jumpsuit','Wrap dress','Romper'], tops:['T-shirt','Blouse','Tank top','Button-up shirt','Cardigan'], bottoms:['Jeans','Shorts','Cargo pants','Linen pants','Joggers'], poses:['Walking naturally along path, arms swinging gently','Standing confidently with feet shoulder-width apart, hands at sides','Leaning on railing overlooking scenery, arms resting','Back to camera, looking over right shoulder','Strolling with relaxed gait, one hand swinging','Walking confidently toward camera, one foot forward mid-stride'], moods:['adventurous exploratory mood','joyful happy mood','carefree lighthearted mood','peaceful serene mood','playful adventurous mood','desert wanderer mood','tropical vibrant mood'], occupations:['Traveler','Photographer','Explorer','Adventurer','Journalist','Content creator'], clothingPresets:['Travel Day Set','Safari Linen Set','Sunset Boardwalk Set','Casual Coffee Run Set','Explorer Jungle Set'] },
  'rainy-day':{ emoji:'🌧️', name:'Rainy Day', cameras:['moody portrait photography','cinematic portrait photography','candid lifestyle photography','film-inspired portrait photography','storytelling lifestyle photography'], props:['Umbrella','Coffee cup','Book','Phone','Flowers','Single flower'], environments:['Rain-slicked street','Cobblestone alley','City street','London phone booth','Park','Cafe','Foggy morning dock','Rain on window view'], lighting:['Overcast light','Foggy atmosphere','Soft diffused light','Reflection light','Warm cafe lighting','Misty light','Foggy lantern glow'], onePieces:['Wrap dress','Sweater dress','Midi dress'], tops:['Turtleneck','Sweater','Cardigan','Trench coat'], bottoms:['Jeans','Leggings','Dress pants'], poses:['Standing in rain, face tilted up, arms slightly out','Walking naturally along path, arms swinging gently','Holding coffee cup with both hands near face','Leaning against wall with one shoulder, arms relaxed','Strolling with relaxed gait, one hand swinging'], moods:['introspective quiet mood','romantic cozy mood','melancholic wistful mood','peaceful serene mood','nostalgic reflective mood','cinematic dramatic mood'], occupations:['Writer','Photographer','Artist','Journalist'], clothingPresets:['Casual Coffee Run Set','Cozy At-Home Set','Winter Coat Set'] },
  'desert':{ emoji:'🏜️', name:'Desert', cameras:['cinematic portrait photography','environmental portrait photography','outdoor golden hour photography','travel editorial photography','documentary lifestyle photography','fine art portrait photography'], props:['Map','Compass','Lantern','Water bottle','Camera','Blanket','Camp lantern','Telescope','Binoculars'], environments:['Desert dunes','Desert oasis','Sahara star camp','Moroccan desert camp','Bedouin tent camp','Desert moonrise','Monument Valley road','Salt flats mirror','Sandstone arch formation','White sands desert','Desert campfire circle','Dubai desert safari','Desert canyon at sunset'], lighting:['Golden hour sunset','Desert midday sun','Dramatic sunset','Warm amber lighting','Campfire glow','Dawn light','Starry night sky','Moonlight'], onePieces:['Wrap dress','Shirt dress','Kaftan','Caftan'], tops:['Button-up shirt','Tank top','Blouse','Vest','Poncho'], bottoms:['Cargo pants','Linen pants','Shorts','High-waisted shorts','Sarong'], poses:['Standing confidently with feet shoulder-width apart, hands at sides','Walking away from camera, natural stride','Windswept pose standing with hair blowing, feet planted','Back to camera, looking over right shoulder','Sitting comfortably with legs to one side, leaning on hand'], moods:['desert wanderer mood','adventurous exploratory mood','bold daring mood','peaceful serene mood','wild untamed mood','earthy grounded mood'], occupations:['Explorer','Adventurer','Traveler','Photographer','Survivalist'], clothingPresets:['Safari Linen Set','Western Cowgirl Set','Explorer Jungle Set'] }
};

// ==========================================
// STYLE_MODES — prompt style suffixes
// ==========================================
const STYLE_MODES = { 'Default':'', 'Cinematic':'cinematic, dramatic', 'Fantasy':'whimsical, fantastical', 'Romantic':'romantic, dreamy', 'Epic':'epic, grand', 'Documentary':'documentary, realistic', 'Anime':'anime art style, vibrant colors, cel-shaded', 'Noir':'noir, high contrast, dramatic shadows', 'Gothic':'gothic aesthetic, dark tones, dramatic shadows', 'Steampunk':'steampunk, Victorian, brass and copper tones', 'Cyberpunk':'cyberpunk, neon-lit, dystopian future', 'Mythological':'mythological, epic, divine lighting', 'Cozy':'cozy, warm tones, soft bokeh', 'Vintage':'vintage film grain, retro color grading' };

// ==========================================
// SEARCH_SYNONYMS — theme search expansion
// ==========================================
const SEARCH_SYNONYMS = {
  'sunset':['golden hour','dusk'], 'beach':['seaside','shore','coast','ocean','vacation'],
  'forest':['woods','jungle','nature','trees'], 'mountain':['alpine','peak','hiking'],
  'city':['urban','downtown','street'], 'snow':['snowy','winter','christmas'],
  'fantasy':['elf','fairy','dragon','enchanted','magic'], 'gym':['fitness','workout','yoga'],
  'art':['creative','studio','gallery','paint'], 'food':['dining','restaurant','cafe','coffee'],
  'wedding':['bridal','bride','marriage','ceremony'], 'autumn':['fall','harvest','leaves','pumpkin'],
  'party':['holiday','celebration','festive','events'], 'swim':['pool','water','surfing','ocean'],
  'street':['urban','graffiti','city','downtown'],
  'steampunk':['Victorian','clockwork','brass','gears'],
  'cyberpunk':['neon','hacker','dystopia','futuristic'],
  'gothic':['dark','haunted','vampire','cemetery'],
  'western':['cowboy','saloon','frontier','ranch'],
  'mythology':['greek','gods','olympus','ancient'],
  'pirate':['ship','treasure','caribbean','sailor'],
  'viking':['norse','nordic','fjord','shield maiden'],
  'cottagecore':['cottage','pastoral','mushroom','wildflower'],
  'anime':['manga','kawaii','japan','sakura'],
  'dark academia':['library','gothic','books','university'],
  'superhero':['hero','cape','powers','marvel'],
  'scifi':['space','alien','robot','starship'],
  'japan':['tokyo','kyoto','anime','sakura','japanese'],
  'europe':['paris','london','rome','venice','prague','amsterdam'],
  'tropical':['bali','fiji','caribbean','island','lagoon','palm'],
  'desert':['sahara','dunes','oasis','bedouin','monument valley','arid'],
  'african':['savanna','safari','serengeti','cape town','zanzibar'],
  'ancient':['ruins','temple','pyramid','machu picchu','angkor','petra'],
  'cozy':['cottage','fireplace','cabin','warm','hygge','candlelit'],
  'rain':['rainy','storm','umbrella','wet','monsoon'],
  'night':['midnight','moonlit','starry','nocturnal','evening']
};
